# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentproject

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mlprojectt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a5b3e237c3f24088af4904f5e67e458f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_008adcbb08a24e6ca1ae762c8a721020 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mlprojectt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a5b3e237c3f24088af4904f5e67e458f }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentproject'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_86aa9d99d0864f4dbcc6330e4aec6b99 }}
        images: 'mlprojectt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a5b3e237c3f24088af4904f5e67e458f }}/mltest:${{ github.sha }}'